version: "3.9" 

services: 
  prometheus: 
    image: prom/prometheus:latest 
    container_name: prometheus 
    volumes: - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    ports: - "10.13.37.1:9090:9090" 
    restart: unless-stopped 
  node_exporter: 
    image: prom/node-exporter:latest 
    container_name: node_exporter 
    ports: - "10.13.37.1:9100:9100" 
    restart: unless-stopped 
  grafana: 
    image: grafana/grafana:latest 
    container_name: grafana 
    ports: - "10.13.37.1:3000:3000" 
    restart: unless-stopped